### ISSUE TITLE
Corrupt PDF

### ISSUE THREAD

**Issue by abdu355** [Ideolys/carbone-env-docker#1]
Used the recommended Dockerfile, getting a corrupt PDF every time i render a report.

```
FROM node:8

WORKDIR /tmp
RUN wget http://download.documentfoundation.org/libreoffice/stable/6.1.5/deb/x86_64/LibreOffice_6.1.5_Linux_x86-64_deb.tar.gz -O libo.tar.gz
RUN apt update \
    && apt install -y libxinerama1 libfontconfig1 libdbus-glib-1-2 libcairo2 libcups2 libglu1-mesa libsm6 unzip \
    && tar -zxvf libo.tar.gz
WORKDIR LibreOffice_6.1.5.2_Linux_x86-64_deb/DEBS
RUN dpkg -i *.deb

WORKDIR /home/node

COPY package.json .
RUN npm install --quiet

COPY . .

```
![image](https://user-images.githubusercontent.com/12097274/57587978-89084500-751e-11e9-8d96-91fd8a9d0e98.png)

**Comment by viincenb** [comment]
Could you please provide your template and your data ?

**Comment by abdu355** [comment]
**Data:**
`const dataJSON = {
  id: 42,
  firstName: "abdusah",
  profession: "engineer",
  ID: "12032193",
  date: 1492012745,
  company: {
    name: "myCompany",
    address: "here",
    city: "Notfar",
    postalCode: 123456
  },
  customer: {
    name: "myCustomer",
    address: "there",
    city: "Faraway",
    postalCode: 654321
  },
  products: [
    {
      name: "product 1",
      priceUnit: 0.1,
      quantity: 10,
      priceTotal: 1
    },
    {
      name: "product 2",
      priceUnit: 0.2,
      quantity: 20,
      priceTotal: 4
    },
    {
      name: "product 3",
      priceUnit: 0.3,
      quantity: 30,
      priceTotal: 9
    }
  ],
  total: 14
};`

**Template + Result files :** https://we.tl/t-Sj1hcecefW
