### ISSUE TITLE
How to add fonts?

### ISSUE THREAD

**Issue by hendri-tobing** [Ideolys/carbone-env-docker#2]
I want to add a font to the docker/libreoffice. How to add the fonts to there? 

I have tried adding font at /usr/share/fonts/truetype/ and clear cache, then restart the docker, but the result is still not as expected.

Thank you.

**Comment by steevepay** [comment]
Hello @hendri-tobing,
Try the following paths:
- `/usr/share/fonts`
- `/usr/local/share/fonts`
- `~/.fonts`

You should add fonts before LibreOffice starts, let me know if it is working.

**Comment by hendri-tobing** [comment]
Hi @steevepay, thank you for the prompt response. I have tried the above paths, then I run clear cache ```fc-cache -f -v```. But still, the pdf produced is not using the font, although the template is using it.
